name: CI & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          docker build -t localhost:5001/myproject:${{ github.sha }} .
          docker push localhost:5001/myproject:${{ github.sha }}
      - name: Deploy via Docker Compose
        run: docker compose up -d