name: Deploy to Cloudflare Tunnel

on:
  push:
    branches: [main]

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  ZONE_ID: ${{ secrets.ZONE_ID }}
  TUNNEL_ID: ${{ secrets.TUNNEL_ID }}
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  DOCKER_HOST: ${{ secrets.DOCKER_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load production environment variables
        run: |
          if [ -f .env.production ]; then
            echo "Loading .env.production..."
            # Load variables and export them to GITHUB_ENV
            while IFS= read -r line; do
              # Skip empty lines and comments
              if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
                # Remove any quotes and export to GITHUB_ENV
                clean_line=$(echo "$line" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
                if [[ "$clean_line" == *"="* ]]; then
                  echo "$clean_line" >> $GITHUB_ENV
                  echo "Loaded: ${clean_line%%=*}"
                fi
              fi
            done < .env.production
          else
            echo "❌ .env.production file not found"
            exit 1
          fi
      
      - name: Validate environment
        run: |
          echo "Checking required variables..."
          
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then echo "❌ CLOUDFLARE_API_TOKEN missing"; exit 1; fi
          if [ -z "$ZONE_ID" ]; then echo "❌ ZONE_ID missing"; exit 1; fi
          if [ -z "$TUNNEL_ID" ]; then echo "❌ TUNNEL_ID missing"; exit 1; fi
          if [ -z "$ACCOUNT_ID" ]; then echo "❌ ACCOUNT_ID missing"; exit 1; fi
          if [ -z "$DOCKER_HOST" ]; then echo "❌ DOCKER_HOST missing"; exit 1; fi
          if [ -z "$APP_PORT" ]; then echo "❌ APP_PORT missing"; exit 1; fi
          
          echo "✅ All variables present"
          echo "- Account ID: ${ACCOUNT_ID:0:8}..."
          echo "- Tunnel ID: ${TUNNEL_ID:0:8}..."
          echo "- Zone ID: ${ZONE_ID:0:8}..."
          echo "- Service: http://$DOCKER_HOST:$APP_PORT"
      
      - name: Test API access
        run: |
          echo "Testing Cloudflare API access..."
          
          # Test token validity
          TOKEN_TEST=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/user/tokens/verify" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN")
          
          TOKEN_VALID=$(echo "$TOKEN_TEST" | jq -r '.success')
          if [ "$TOKEN_VALID" != "true" ]; then
            echo "❌ Invalid API token"
            echo "$TOKEN_TEST" | jq '.errors[]'
            exit 1
          fi
          
          echo "✅ API token valid"
          
          # Test tunnel access
          TUNNEL_TEST=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/cfd_tunnel/$TUNNEL_ID" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN")
          
          TUNNEL_VALID=$(echo "$TUNNEL_TEST" | jq -r '.success')
          if [ "$TUNNEL_VALID" != "true" ]; then
            echo "❌ Cannot access tunnel"
            echo "$TUNNEL_TEST" | jq '.errors[]'
            exit 1
          fi
          
          echo "✅ Tunnel access confirmed"
          echo "Tunnel name: $(echo "$TUNNEL_TEST" | jq -r '.result.name')"
      
      - name: Update tunnel configuration
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          FQDN="${PROJECT_NAME}.${{ env.DOMAIN }}"
          SERVICE="http://$DOCKER_HOST:$APP_PORT"
          
          echo "Updating tunnel configuration for: $FQDN → $SERVICE"
          
          # Get current configuration
          CURRENT_CONFIG=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/cfd_tunnel/$TUNNEL_ID/configurations" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN")
          
          echo "Current config response:"
          echo "$CURRENT_CONFIG" | jq '.'
          
          CONFIG_SUCCESS=$(echo "$CURRENT_CONFIG" | jq -r '.success')
          if [ "$CONFIG_SUCCESS" != "true" ]; then
            echo "❌ Failed to get tunnel configuration"
            echo "$CURRENT_CONFIG" | jq '.errors[]'
            exit 1
          fi
          
          # Extract current config and create updated version
          echo "$CURRENT_CONFIG" | jq -r '.result.config' > current_config.json
          
          # Create new config with updated ingress rules
          jq --arg hostname "$FQDN" --arg service "$SERVICE" '
            # Remove existing rule for this hostname
            .ingress = (.ingress | map(select(.hostname != $hostname))) |
            # Find catch-all rule index (rules without hostname or with http_status)
            (.ingress | map(.hostname == null or (.service | test("http_status:"))) | index(true)) as $catchall_idx |
            # Insert new rule before catch-all
            if $catchall_idx then
              .ingress = (.ingress[:$catchall_idx] + [{"hostname": $hostname, "service": $service}] + .ingress[$catchall_idx:])
            else
              .ingress = .ingress + [{"hostname": $hostname, "service": $service}]
            end
          ' current_config.json > new_config.json
          
          echo "New configuration:"
          cat new_config.json | jq '.'
          
          # Update tunnel configuration
          UPDATE_RESPONSE=$(curl -s -X PUT \
            "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/cfd_tunnel/$TUNNEL_ID/configurations" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "{\"config\": $(cat new_config.json)}")
          
          echo "Update response:"
          echo "$UPDATE_RESPONSE" | jq '.'
          
          UPDATE_SUCCESS=$(echo "$UPDATE_RESPONSE" | jq -r '.success')
          if [ "$UPDATE_SUCCESS" != "true" ]; then
            echo "❌ Failed to update tunnel configuration"
            echo "$UPDATE_RESPONSE" | jq '.errors[]'
            exit 1
          fi
          
          echo "✅ Tunnel configuration updated for $FQDN"
          
          # Cleanup
          rm -f current_config.json new_config.json
      
      - name: Summary
        run: |
          echo "🚀 Deployment completed successfully!"
          echo ""
          echo "Configuration:"
          echo "- Project: ${{ steps.domain.outputs.project }}"
          echo "- Domain: ${{ steps.domain.outputs.fqdn }}"
          echo "- Target: http://$DOCKER_HOST:$APP_PORT"
          echo ""
          echo "Your app should be available at: https://${{ steps.domain.outputs.fqdn }}"
          echo ""
          echo "Note: DNS propagation may take a few minutes."